(define (problem Pick_up_phone)
    (:domain virtualhome)
    (:objects
    character - character
    home_office phone fork desk mouse keyboard cpuscreen mousepad dining_room - object
)
    (:init
    (obj_next_to cpuscreen mousepad)
    (inside_room phone dining_room)
    (grabbable phone)
    (obj_inside mouse home_office)
    (movable mousepad)
    (obj_next_to mousepad mouse)
    (obj_next_to mousepad desk)
    (has_switch phone)
    (grabbable mouse)
    (surfaces mousepad)
    (obj_next_to desk keyboard)
    (obj_next_to phone desk)
    (surfaces desk)
    (has_plug keyboard)
    (obj_next_to desk mouse)
    (movable phone)
    (obj_inside phone home_office)
    (obj_next_to mouse desk)
    (obj_next_to mouse mousepad)
    (obj_ontop phone desk)
    (grabbable fork)
    (obj_ontop keyboard desk)
    (obj_next_to keyboard mouse)
    (clean phone)
    (movable fork)
    (obj_next_to cpuscreen mouse)
    (grabbable keyboard)
    (obj_next_to desk cpuscreen)
    (obj_inside keyboard home_office)
    (obj_ontop mousepad desk)
    (obj_next_to mousepad keyboard)
    (obj_inside mousepad home_office)
    (obj_next_to mouse keyboard)
    (obj_ontop fork desk)
    (obj_next_to cpuscreen desk)
    (has_plug mouse)
    (inside character dining_room)
    (obj_inside cpuscreen home_office)
    (obj_next_to mousepad cpuscreen)
    (obj_next_to desk fork)
    (obj_next_to mouse cpuscreen)
    (plugged_in phone)
    (obj_ontop mouse desk)
    (obj_inside fork home_office)
    (obj_next_to fork desk)
    (obj_inside desk home_office)
    (obj_next_to desk phone)
    (has_plug phone)
    (movable desk)
    (movable mouse)
    (obj_next_to cpuscreen keyboard)
    (obj_ontop cpuscreen desk)
    (obj_next_to keyboard mousepad)
    (movable keyboard)
    (obj_next_to desk mousepad)
    (obj_next_to keyboard desk)
    (obj_ontop mouse mousepad)
    (obj_next_to keyboard cpuscreen)
)
    (:goal
    (and
        (holds_rh character phone)
    )
)
    )
    