(define (problem Read_book)
    (:domain virtualhome)
    (:objects
    character - character
    novel home_office light computer chair dining_room - object
)
    (:init
    (obj_next_to computer light)
    (surfaces chair)
    (has_plug light)
    (has_switch light)
    (facing chair computer)
    (readable novel)
    (obj_next_to light computer)
    (movable chair)
    (obj_next_to light novel)
    (plugged_in light)
    (obj_next_to computer chair)
    (sittable chair)
    (has_switch computer)
    (obj_next_to light chair)
    (obj_next_to light light)
    (obj_inside novel home_office)
    (has_paper novel)
    (obj_next_to novel light)
    (clean light)
    (movable novel)
    (cuttable novel)
    (grabbable chair)
    (obj_next_to chair light)
    (inside character dining_room)
    (grabbable novel)
    (lookable computer)
    (can_open novel)
    (obj_inside computer home_office)
    (off light)
    (obj_inside chair home_office)
    (obj_next_to chair computer)
    (inside_room light dining_room)
    (obj_inside light home_office)
)
    (:goal
    (and
        (holds_rh character novel)
    )
)
    )
    