(define (problem Write_an_email)
    (:domain virtualhome)
    (:objects
    character - character
    keyboard computer mousepad floor dining_room wall home_office powersocket mouse cpuscreen desk chair laptop doorjamb - object
)
    (:init
    (clean laptop)
    (off laptop)
    (plugged_in laptop)
    (surfaces floor)
    (surfaces floor)
    (surfaces floor)
    (grabbable chair)
    (movable chair)
    (sittable chair)
    (surfaces chair)
    (movable desk)
    (surfaces desk)
    (grabbable mouse)
    (has_plug mouse)
    (movable mouse)
    (movable mousepad)
    (surfaces mousepad)
    (grabbable keyboard)
    (has_plug keyboard)
    (movable keyboard)
    (has_switch computer)
    (lookable computer)
    (grabbable laptop)
    (has_plug laptop)
    (has_switch laptop)
    (lookable laptop)
    (movable laptop)
    (next_to powersocket mouse)
    (next_to wall mouse)
    (next_to floor mouse)
    (next_to doorjamb mouse)
    (next_to mouse floor)
    (next_to mouse powersocket)
    (next_to mousepad mouse)
    (next_to desk mouse)
    (next_to computer mouse)
    (next_to cpuscreen mouse)
    (next_to mouse laptop)
    (next_to mouse floor)
    (next_to mouse wall)
    (next_to keyboard mouse)
    (next_to floor mouse)
    (next_to mouse desk)
    (ontop mouse mousepad)
    (inside character dining_room)
    (next_to floor mouse)
    (ontop mouse desk)
    (next_to chair mouse)
    (next_to mouse cpuscreen)
    (next_to mouse mousepad)
    (next_to mouse chair)
    (next_to laptop mouse)
    (next_to mouse computer)
    (next_to mouse wall)
    (next_to mouse keyboard)
    (next_to wall mouse)
    (next_to mouse floor)
    (next_to mouse doorjamb)
    (next_to wall mouse)
    (next_to mouse wall)
)
    (:goal
    (and
        (on laptop)
    )
)
    )
    